apiVersion: v1
kind: Service
metadata:
  name: engine-headless
  labels:
    app: engine
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: engine
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: engine
spec:
  serviceName: "engine-headless"
  replicas: 3
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        # image: ghcr.io/viquitorreis/distributed_matching_engine:latest
        image: engine:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: REPLICA_COUNT
          value: "3"
        - name: SERVICE_NAME
          value: "engine-headless"
        - name: STORAGE_DIR
          value: "/app/data"
        volumeMounts:
        - name: data
          mountPath: /app/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi